### ISSUE TITLE
Cargo Folder Icons?

### ISSUE THREAD

**Issue by justanotherbyte** [tal7aouy/vscode-icons#3]
Hey there, I love your icon extension. I was wondering if you could add an icon set for the `.cargo` folder? Preferrably the icon would be the `crates.io` icon.

`.cargo` is for the Rust programming language.

**Comment by tal7aouy** [comment]
Hi, I will add it in version 3.
folder example
![folder_rust](https://user-images.githubusercontent.com/79597452/154856033-0d8498a1-ca9d-4b21-ad47-2a28dc261820.svg)
![folder_rust_open](https://user-images.githubusercontent.com/79597452/154856099-efb827ee-cfef-4a58-8447-89283be27ca8.svg)

**Comment by justanotherbyte** [comment]
Sounds good
