### ISSUE TITLE
The NestJS files always display an A (Angular) icon.

### ISSUE THREAD

**Issue by guotingchao** [tal7aouy/vscode-icons#32]
"How can I trigger NestJS to display like the example image?"

**Comment by guotingchao** [comment]
Hi, I checked the source code and it doesn't seem to have any connection to Nest-sercice, Nest-controller or other file icons as in the README icon presentation screen. Is it still in continuous integration? Very nice icons Looking forward to your reply.

**Comment by tal7aouy** [comment]
Hi
Thank you for your contribution , we are still working on this icons to make it better

**Comment by guotingchao** [comment]
Thank you for your reply. I understand the current situation. I will close this issue first and wait for you to re-reopen during any update period. 😊
